In [1]:
import numpy as np
import pandas as pd

In [ ]:
# pandas series is a 1D data structure, like a list or numpy array, the main difference is that the pandas series also has index along with the value.
# we can create pandas series from a list, 
# pandas series accepts heterogeneous data types

In [2]:
list01 = ['Anna', 'Maria', 'Elena', 'Katya']
list01

['Anna', 'Maria', 'Elena', 'Katya']

In [3]:
pd.Series(list01)

0     Anna
1    Maria
2    Elena
3    Katya
dtype: object

In [5]:
srs2 = pd.Series([3, 1, 2, 3, 2])
srs2

0    3
1    1
2    2
3    3
4    2
dtype: int64

In [7]:
srs1 = pd.Series([3.0, 1, 2, 3, 2])
srs1

0    3.0
1    1.0
2    2.0
3    3.0
4    2.0
dtype: float64

In [10]:
srs1 = pd.Series([3.4, 7, 'hello', False])
srs1

0      3.4
1        7
2    hello
3    False
dtype: object

In [11]:
type(srs1[0])

float

In [12]:
type(srs1[1])

int

In [13]:
type(srs1[2])

str

In [14]:
type(srs1[3])

bool

In [16]:
srs2 = pd.Series([5.7, 2, 2.01], index  = ['Kateryna', 'Mehmet', 'Rovshen'])
srs2

Kateryna    5.70
Mehmet      2.00
Rovshen     2.01
dtype: float64

In [18]:
arr1 = np.arange(1, 21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
pd.Series(arr1)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
dtype: int64

In [20]:
arr2 = np.arange(1, 21).reshape(4, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
pd.Series(arr2)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 5) instead

In [24]:
pd.DataFrame(arr2)

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20

In [ ]:
# Create a 5x5 matrix(2D array) with random values then convert it to a dataframe

In [25]:
import random

In [38]:
data = np.random.randint(1, 100, 25).reshape(5,5)
df = pd.DataFrame(data, index = ['r1','r2','r3','r4', 'r5'], columns = ['col1','col2','col3','col4', 'col5'])
df

    col1  col2  col3  col4  col5
r1    18    51    80    86    64
r2    48    25    73    88    86
r3    89    39    16    31    88
r4    42    70    27    80    58
r5    45    62    56    86    17

In [40]:
data = {
    "StudentID": ["S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008", "S009", "S010"],
    "Name": ["John", "Emily", "Alex", "Sophia", "Michael", "Isabella", "Daniel", "Olivia", "David", "Emma"],
    "Age": [20, 21, np.nan, 22, 20, 21, 23, 19, 22, np.nan],
    "Major": ["Math", "Computer Science", "Computer Science", np.nan, "Math",
              "Biology", np.nan, "Biology", "Math", "Computer Science"],
    "GPA": [2.5, 1.8, 2.2, 3.7, 3.6, 3.9, 3.1, 1.4, 3.3, np.nan],
    "Exam1": [40, 23, 33, 76, 89, 92, 64, 28, 85, np.nan],
    "Exam2": [52, 38, 51, 93, 62, 87, 77, 49, 80, np.nan],
    "Lecture": ["Calculus", "Algorithms", "Algorithms", "Genetics", "Linear Algebra",
                "Microbiology", "Electromagnetism", "Microbiology", "Probability",np.nan],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"]
}
students_df = pd.DataFrame(data)
# Display the DataFrame
students_df

,StudentID,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender
0,S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M
1,S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F
2,S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M
3,S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F
4,S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M
5,S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F
6,S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M
7,S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F
8,S009,David,22.0,Math,3.3,85.0,80.0,Probability,M
9,S010,Emma,NaN,Computer Science,NaN,NaN,NaN,NaN,F

In [41]:
students_df.head()

,StudentID,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender
0,S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M
1,S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F
2,S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M
3,S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F
4,S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M

In [43]:
students_df.sample(5)

,StudentID,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender
0,S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M
4,S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M
6,S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M
2,S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M
1,S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F

In [45]:
students_df.tail()

,StudentID,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender
5,S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F
6,S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M
7,S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F
8,S009,David,22.0,Math,3.3,85.0,80.0,Probability,M
9,S010,Emma,NaN,Computer Science,NaN,NaN,NaN,NaN,F

In [46]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     object
 1   Name       10 non-null     object
 2   Age        8 non-null      float64
 3   Major      8 non-null      object
 4   GPA        9 non-null      float64
 5   Exam1      9 non-null      float64
 6   Exam2      9 non-null      float64
 7   Lecture    9 non-null      object
 8   Gender     10 non-null     object
dtypes: float64(4), object(5)
memory usage: 852.0+ bytes

In [47]:
students_df.columns

Index(['StudentID', 'Name', 'Age', 'Major', 'GPA', 'Exam1', 'Exam2', 'Lecture',
       'Gender'],
      dtype='object')

In [48]:
students_df.index

RangeIndex(start=0, stop=10, step=1)

In [49]:
students_df.shape

(10, 9)

In [50]:
students_df

,StudentID,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender
0,S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M
1,S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F
2,S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M
3,S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F
4,S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M
5,S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F
6,S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M
7,S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F
8,S009,David,22.0,Math,3.3,85.0,80.0,Probability,M
9,S010,Emma,NaN,Computer Science,NaN,NaN,NaN,NaN,F

In [ ]:
# A dataframe is multiple series aligned with eachother.
students_df['Major'] 
# this is the preferred way of selecting a column 
# because sometimes names of columns can have spaces in them.

0                Math
1    Computer Science
2    Computer Science
3                 NaN
4                Math
5             Biology
6                 NaN
7             Biology
8                Math
9    Computer Science
Name: Major, dtype: object

In [53]:
students_df.Major

0                Math
1    Computer Science
2    Computer Science
3                 NaN
4                Math
5             Biology
6                 NaN
7             Biology
8                Math
9    Computer Science
Name: Major, dtype: object

In [55]:
students_df.Major.value_counts()
# will give you unique values in this column along with their respective frequencies

Major
Math                3
Computer Science    3
Biology             2
Name: count, dtype: int64

In [56]:
students_df.Major.value_counts(dropna = False)

Major
Math                3
Computer Science    3
NaN                 2
Biology             2
Name: count, dtype: int64

In [57]:
students_df.Major.value_counts(dropna = False, normalize = True)

Major
Math                0.3
Computer Science    0.3
NaN                 0.2
Biology             0.2
Name: proportion, dtype: float64

In [61]:
# create a new column as average of Exam1 and Exam2
students_df['Average'] = (students_df['Exam1'] + students_df['Exam2']) / 2
students_df

,StudentID,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
0,S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M,46.0
1,S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
2,S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
3,S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
4,S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
5,S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
6,S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5
7,S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F,38.5
8,S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5
9,S010,Emma,NaN,Computer Science,NaN,NaN,NaN,NaN,F,NaN

In [62]:
students_df.set_index('StudentID', inplace = True)
students_df

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M,46.0
S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5
S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F,38.5
S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5
S010,Emma,NaN,Computer Science,NaN,NaN,NaN,NaN,F,NaN

In [ ]:
# Drop the data of S010 as the values are not predictable
students_df.drop('S010', inplace = True)
students_df

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M,46.0
S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5
S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F,38.5
S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5

In [71]:
students_df

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M,46.0
S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5
S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F,38.5
S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5

In [72]:
students_df.iloc[2:5]

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S003,Alex,NaN,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5

In [73]:
students_df.loc['S005':'S007']

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5

In [75]:
# find how many null values there are in each column with isnull
students_df.isnull().sum()

Name       0
Age        1
Major      2
GPA        0
Exam1      0
Exam2      0
Lecture    0
Gender     0
Average    0
dtype: int64

In [ ]:
# using conditional selection we can find exactly where the null value is 
students_df.loc[students_df['Major'].isnull()]
# go to the dataframe and locate wherever the Major column is null

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5

In [ ]:
students_df['Name'].loc[students_df['Major'].isnull()]

StudentID
S004    Sophia
S007    Daniel
Name: Name, dtype: object

In [87]:
students_df.loc[students_df['Major'].isnull(), 'Name']

StudentID
S004    Sophia
S007    Daniel
Name: Name, dtype: object

In [88]:
students_df.loc[students_df['Major'].isnull(), 'Average']

StudentID
S004    84.5
S007    70.5
Name: Average, dtype: float64

In [90]:
students_df.loc[students_df['Major'].isnull(), ['Name', 'Average']]

             Name  Average
StudentID
S004       Sophia     84.5
S007       Daniel     70.5

In [92]:
# find students who are older than 20 yrs old
students_df.loc[students_df.Age > 20]

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5
S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5

In [102]:
# find the average age of students
students_df.Age.mean()
# this technique will select all the rows in this column.
# you cannot select spesific rows

np.float64(21.0)

In [96]:
students_df['Age'].mean()

np.float64(21.0)

In [100]:
students_df.loc[:, 'Age']

StudentID
S001    20.0
S002    21.0
S003     NaN
S004    22.0
S005    20.0
S006    21.0
S007    23.0
S008    19.0
S009    22.0
Name: Age, dtype: float64

In [101]:
students_df.loc[:, 'Age'].mean()

np.float64(21.0)

In [106]:
students_df.loc['S007', 'Age']

np.float64(23.0)

In [107]:
students_df.isnull().sum()

Name       0
Age        1
Major      2
GPA        0
Exam1      0
Exam2      0
Lecture    0
Gender     0
Average    0
dtype: int64

In [ ]:
# As we have null values in two different columns, while one is a categorical column, 
# the other one stores numerical data
# We must apply appropriate methods for each 
# For Age, which is a numerical column, and the age must be close to the other students, 
# we use average to fill the null value
students_df.Age.fillna(students_df.Age.mean(), inplace = True)
students_df

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M,46.0
S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
S003,Alex,21.0,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
S004,Sophia,22.0,NaN,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5
S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F,38.5
S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5

In [ ]:
# For categorical columns, if the distribution is unbalanced, 
# meaning if one value is repeated too many times eg. 100, 
# and the other categories are repeated less, then we use mode = most frequent, 
# otherwise bfill and ffill are techniques that randomly fill null values.

In [ ]:
students_df['Major'].fillna(students_df['Major'].mode()[0])

StudentID
S001                Math
S002    Computer Science
S003    Computer Science
S004                Math
S005                Math
S006             Biology
S007                Math
S008             Biology
S009                Math
Name: Major, dtype: object

In [111]:
students_df.loc['S004', 'Major'] = 'Biology'
students_df

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M,46.0
S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
S003,Alex,21.0,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
S004,Sophia,22.0,Biology,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,NaN,3.1,64.0,77.0,Electromagnetism,M,70.5
S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F,38.5
S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5

In [113]:
students_df.iloc[6, 2] = 'Physics'
students_df

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S001,John,20.0,Math,2.5,40.0,52.0,Calculus,M,46.0
S002,Emily,21.0,Computer Science,1.8,23.0,38.0,Algorithms,F,30.5
S003,Alex,21.0,Computer Science,2.2,33.0,51.0,Algorithms,M,42.0
S004,Sophia,22.0,Biology,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5
S007,Daniel,23.0,Physics,3.1,64.0,77.0,Electromagnetism,M,70.5
S008,Olivia,19.0,Biology,1.4,28.0,49.0,Microbiology,F,38.5
S009,David,22.0,Math,3.3,85.0,80.0,Probability,M,82.5

In [ ]:
students_df.loc[:,['Name', 'Major']]

               Name             Major
StudentID
S001           John              Math
S002          Emily  Computer Science
S003           Alex  Computer Science
S004         Sophia           Biology
S005        Michael              Math
S006       Isabella           Biology
S007         Daniel           Physics
S008         Olivia           Biology
S009          David              Math

In [119]:
students_df.iloc[:, [0, 2]]

               Name             Major
StudentID
S001           John              Math
S002          Emily  Computer Science
S003           Alex  Computer Science
S004         Sophia           Biology
S005        Michael              Math
S006       Isabella           Biology
S007         Daniel           Physics
S008         Olivia           Biology
S009          David              Math

In [120]:
# select columns Name and Major without using loc or iloc
students_df['Name', 'Major']

KeyError: ('Name', 'Major')

In [121]:
students_df[['Name', 'Major']]

               Name             Major
StudentID
S001           John              Math
S002          Emily  Computer Science
S003           Alex  Computer Science
S004         Sophia           Biology
S005        Michael              Math
S006       Isabella           Biology
S007         Daniel           Physics
S008         Olivia           Biology
S009          David              Math

In [122]:
students_df.loc['S002':'S005', 'Name':'Major']

              Name   Age             Major
StudentID
S002         Emily  21.0  Computer Science
S003          Alex  21.0  Computer Science
S004        Sophia  22.0           Biology
S005       Michael  20.0              Math

In [127]:
students_df.iloc[1:5, 0:3]

              Name   Age             Major
StudentID
S002         Emily  21.0  Computer Science
S003          Alex  21.0  Computer Science
S004        Sophia  22.0           Biology
S005       Michael  20.0              Math

In [130]:
# Get the student names, average scores and respective majors where their average scores are more than 80
students_df[['Name', 'Average', 'Major']][students_df.Average > 80]

               Name  Average    Major
StudentID
S004         Sophia     84.5  Biology
S006       Isabella     89.5  Biology
S009          David     82.5     Math

In [132]:
students_df.loc[students_df.Average > 80, ['Name', 'Average', 'Major']]

               Name  Average    Major
StudentID
S004         Sophia     84.5  Biology
S006       Isabella     89.5  Biology
S009          David     82.5     Math

In [133]:
# select the students whose GPAs are more than 3.5
students_df[students_df.GPA > 3.5]

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S004,Sophia,22.0,Biology,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5

In [134]:
students_df.loc[students_df.GPA > 3.5]

,Name,Age,Major,GPA,Exam1,Exam2,Lecture,Gender,Average
StudentID,,,,,,,,,
S004,Sophia,22.0,Biology,3.7,76.0,93.0,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,89.0,62.0,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,92.0,87.0,Microbiology,F,89.5

In [137]:
# select the students name and GPA whose GPA is greater than 3.5 and sort them by GPA
students_df[['Name', 'GPA']][students_df.GPA > 3.5].sort_values('GPA')

               Name  GPA
StudentID
S005        Michael  3.6
S004         Sophia  3.7
S006       Isabella  3.9

In [138]:
students_df.loc[students_df.GPA > 3.5, ['Name', 'GPA']].sort_values('GPA')

               Name  GPA
StudentID
S005        Michael  3.6
S004         Sophia  3.7
S006       Isabella  3.9

In [ ]:
# Delete the Exam1 and Exam2 columns from the dataframe
students_df.drop(['Exam1', 'Exam2'], axis = 1, inplace = True)
students_df

,Name,Age,Major,GPA,Lecture,Gender,Average
StudentID,,,,,,,
S001,John,20.0,Math,2.5,Calculus,M,46.0
S002,Emily,21.0,Computer Science,1.8,Algorithms,F,30.5
S003,Alex,21.0,Computer Science,2.2,Algorithms,M,42.0
S004,Sophia,22.0,Biology,3.7,Genetics,F,84.5
S005,Michael,20.0,Math,3.6,Linear Algebra,M,75.5
S006,Isabella,21.0,Biology,3.9,Microbiology,F,89.5
S007,Daniel,23.0,Physics,3.1,Electromagnetism,M,70.5
S008,Olivia,19.0,Biology,1.4,Microbiology,F,38.5
S009,David,22.0,Math,3.3,Probability,M,82.5

In [147]:
students_df.groupby('Major')['GPA'].mean()

Major
Biology             3.000000
Computer Science    2.000000
Math                3.133333
Physics             3.100000
Name: GPA, dtype: float64

In [148]:
students_df.groupby('Major')[['GPA']].mean()

                       GPA
Major
Biology           3.000000
Computer Science  2.000000
Math              3.133333
Physics           3.100000

In [149]:
students_df.groupby('Major')[['Age']].agg(['min', 'max', 'mean', 'median'])

                   Age
                   min   max       mean median
Major
Biology           19.0  22.0  20.666667   21.0
Computer Science  21.0  21.0  21.000000   21.0
Math              20.0  22.0  20.666667   20.0
Physics           23.0  23.0  23.000000   23.0

In [150]:
students_df.groupby('Lecture')[['Average']].agg(['min', 'max', 'mean', 'median'])

                 Average
                     min   max   mean median
Lecture
Algorithms          30.5  42.0  36.25  36.25
Calculus            46.0  46.0  46.00  46.00
Electromagnetism    70.5  70.5  70.50  70.50
Genetics            84.5  84.5  84.50  84.50
Linear Algebra      75.5  75.5  75.50  75.50
Microbiology        38.5  89.5  64.00  64.00
Probability         82.5  82.5  82.50  82.50

In [151]:
students_df.groupby(['Major', 'Lecture'])[['Average']].agg(['min', 'max', 'mean', 'median'])

                                  Average
                                      min   max   mean median
Major            Lecture
Biology          Genetics            84.5  84.5  84.50  84.50
                 Microbiology        38.5  89.5  64.00  64.00
Computer Science Algorithms          30.5  42.0  36.25  36.25
Math             Calculus            46.0  46.0  46.00  46.00
                 Linear Algebra      75.5  75.5  75.50  75.50
                 Probability         82.5  82.5  82.50  82.50
Physics          Electromagnetism    70.5  70.5  70.50  70.50

In [152]:
students_df[['GPA', 'Average']].corr()

              GPA   Average
GPA      1.000000  0.954053
Average  0.954053  1.000000

In [153]:
students_df['situation'] = students_df['Average'].apply(lambda x: 'Passed' if x >= 60 else 'Failed')

In [154]:
students_df

,Name,Age,Major,GPA,Lecture,Gender,Average,situation
StudentID,,,,,,,,
S001,John,20.0,Math,2.5,Calculus,M,46.0,Failed
S002,Emily,21.0,Computer Science,1.8,Algorithms,F,30.5,Failed
S003,Alex,21.0,Computer Science,2.2,Algorithms,M,42.0,Failed
S004,Sophia,22.0,Biology,3.7,Genetics,F,84.5,Passed
S005,Michael,20.0,Math,3.6,Linear Algebra,M,75.5,Passed
S006,Isabella,21.0,Biology,3.9,Microbiology,F,89.5,Passed
S007,Daniel,23.0,Physics,3.1,Electromagnetism,M,70.5,Passed
S008,Olivia,19.0,Biology,1.4,Microbiology,F,38.5,Failed
S009,David,22.0,Math,3.3,Probability,M,82.5,Passed

In [155]:
students_df.groupby(['Gender', 'situation'])[['situation']].value_counts()

Gender  situation
F       Failed       2
        Passed       2
M       Failed       2
        Passed       3
Name: count, dtype: int64

In [156]:
students_df.filter(items = ['Name', 'Major', 'GPA'])

               Name             Major  GPA
StudentID
S001           John              Math  2.5
S002          Emily  Computer Science  1.8
S003           Alex  Computer Science  2.2
S004         Sophia           Biology  3.7
S005        Michael              Math  3.6
S006       Isabella           Biology  3.9
S007         Daniel           Physics  3.1
S008         Olivia           Biology  1.4
S009          David              Math  3.3

In [158]:
students_df.groupby('Major')['GPA'].mean()

Major
Biology             3.000000
Computer Science    2.000000
Math                3.133333
Physics             3.100000
Name: GPA, dtype: float64

In [161]:
students_df.groupby('Major').filter(lambda x: x['GPA'].mean() > 3)

,Name,Age,Major,GPA,Lecture,Gender,Average,situation
StudentID,,,,,,,,
S001,John,20.0,Math,2.5,Calculus,M,46.0,Failed
S005,Michael,20.0,Math,3.6,Linear Algebra,M,75.5,Passed
S007,Daniel,23.0,Physics,3.1,Electromagnetism,M,70.5,Passed
S009,David,22.0,Math,3.3,Probability,M,82.5,Passed

In [162]:
students_df.where(students_df['GPA'] > 3)

,Name,Age,Major,GPA,Lecture,Gender,Average,situation
StudentID,,,,,,,,
S001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S004,Sophia,22.0,Biology,3.7,Genetics,F,84.5,Passed
S005,Michael,20.0,Math,3.6,Linear Algebra,M,75.5,Passed
S006,Isabella,21.0,Biology,3.9,Microbiology,F,89.5,Passed
S007,Daniel,23.0,Physics,3.1,Electromagnetism,M,70.5,Passed
S008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S009,David,22.0,Math,3.3,Probability,M,82.5,Passed

In [163]:
students_df.where(students_df['GPA'] > 3).dropna()

,Name,Age,Major,GPA,Lecture,Gender,Average,situation
StudentID,,,,,,,,
S004,Sophia,22.0,Biology,3.7,Genetics,F,84.5,Passed
S005,Michael,20.0,Math,3.6,Linear Algebra,M,75.5,Passed
S006,Isabella,21.0,Biology,3.9,Microbiology,F,89.5,Passed
S007,Daniel,23.0,Physics,3.1,Electromagnetism,M,70.5,Passed
S009,David,22.0,Math,3.3,Probability,M,82.5,Passed

In [165]:
students_df.where((students_df['Lecture'] == 'Algorithms') & (students_df['Average'] < 40)).dropna()

,Name,Age,Major,GPA,Lecture,Gender,Average,situation
StudentID,,,,,,,,
S002,Emily,21.0,Computer Science,1.8,Algorithms,F,30.5,Failed

In [166]:
gender_map = {'M': 1, 'F': 0}
students_df['Gender_Code'] = students_df['Gender'].map(gender_map)

In [167]:
students_df

,Name,Age,Major,GPA,Lecture,Gender,Average,situation,Gender_Code
StudentID,,,,,,,,,
S001,John,20.0,Math,2.5,Calculus,M,46.0,Failed,1
S002,Emily,21.0,Computer Science,1.8,Algorithms,F,30.5,Failed,0
S003,Alex,21.0,Computer Science,2.2,Algorithms,M,42.0,Failed,1
S004,Sophia,22.0,Biology,3.7,Genetics,F,84.5,Passed,0
S005,Michael,20.0,Math,3.6,Linear Algebra,M,75.5,Passed,1
S006,Isabella,21.0,Biology,3.9,Microbiology,F,89.5,Passed,0
S007,Daniel,23.0,Physics,3.1,Electromagnetism,M,70.5,Passed,1
S008,Olivia,19.0,Biology,1.4,Microbiology,F,38.5,Failed,0
S009,David,22.0,Math,3.3,Probability,M,82.5,Passed,1

In [168]:
students_df['Age_Group'] = students_df['Age'].apply(lambda x: '3.Grade' if x<21 else '4.Grade')

In [169]:
students_df

,Name,Age,Major,GPA,Lecture,Gender,Average,situation,Gender_Code,Age_Group
StudentID,,,,,,,,,,
S001,John,20.0,Math,2.5,Calculus,M,46.0,Failed,1,3.Grade
S002,Emily,21.0,Computer Science,1.8,Algorithms,F,30.5,Failed,0,4.Grade
S003,Alex,21.0,Computer Science,2.2,Algorithms,M,42.0,Failed,1,4.Grade
S004,Sophia,22.0,Biology,3.7,Genetics,F,84.5,Passed,0,4.Grade
S005,Michael,20.0,Math,3.6,Linear Algebra,M,75.5,Passed,1,3.Grade
S006,Isabella,21.0,Biology,3.9,Microbiology,F,89.5,Passed,0,4.Grade
S007,Daniel,23.0,Physics,3.1,Electromagnetism,M,70.5,Passed,1,4.Grade
S008,Olivia,19.0,Biology,1.4,Microbiology,F,38.5,Failed,0,3.Grade
S009,David,22.0,Math,3.3,Probability,M,82.5,Passed,1,4.Grade

In [170]:
# DataFrame 1: Basic computer specifications
df_computers1 = pd.DataFrame({
    'ComputerID': ['C001', 'C002', 'C003', 'C004'],
    'Brand': ['Dell', 'HP', 'Apple', 'Lenovo'],
    'Model': ['Inspiron', 'Pavilion', 'MacBook', 'ThinkPad'],
    'Processor': ['Intel i5', 'Intel i7', 'M1', 'AMD Ryzen 5'],
    'RAM': ['8GB', '16GB', '8GB', '16GB']
})

In [171]:
df_computers1

  ComputerID   Brand     Model    Processor   RAM
0       C001    Dell  Inspiron     Intel i5   8GB
1       C002      HP  Pavilion     Intel i7  16GB
2       C003   Apple   MacBook           M1   8GB
3       C004  Lenovo  ThinkPad  AMD Ryzen 5  16GB

In [172]:
df_computers2 = pd.DataFrame({
    'ComputerID': ['C006', 'C007', 'C008', 'C009'],
    'Brand': ['Asus', 'Acer', 'Microsoft', 'Samsung'],
    'Model': ['ZenBook', 'Aspire', 'Surface', 'Galaxy Book'],
    'Processor': ['Intel i9', 'AMD Ryzen 7', 'Intel i5', 'Intel i7'],
    'RAM': ['16GB', '8GB', '8GB', '16GB']
})
df_computers2

  ComputerID      Brand        Model    Processor   RAM
0       C006       Asus      ZenBook     Intel i9  16GB
1       C007       Acer       Aspire  AMD Ryzen 7   8GB
2       C008  Microsoft      Surface     Intel i5   8GB
3       C009    Samsung  Galaxy Book     Intel i7  16GB

In [173]:
pd.concat([df_computers1, df_computers2])

  ComputerID      Brand        Model    Processor   RAM
0       C001       Dell     Inspiron     Intel i5   8GB
1       C002         HP     Pavilion     Intel i7  16GB
2       C003      Apple      MacBook           M1   8GB
3       C004     Lenovo     ThinkPad  AMD Ryzen 5  16GB
0       C006       Asus      ZenBook     Intel i9  16GB
1       C007       Acer       Aspire  AMD Ryzen 7   8GB
2       C008  Microsoft      Surface     Intel i5   8GB
3       C009    Samsung  Galaxy Book     Intel i7  16GB

In [174]:
pd.concat([df_computers1,df_computers2], ignore_index=True)

  ComputerID      Brand        Model    Processor   RAM
0       C001       Dell     Inspiron     Intel i5   8GB
1       C002         HP     Pavilion     Intel i7  16GB
2       C003      Apple      MacBook           M1   8GB
3       C004     Lenovo     ThinkPad  AMD Ryzen 5  16GB
4       C006       Asus      ZenBook     Intel i9  16GB
5       C007       Acer       Aspire  AMD Ryzen 7   8GB
6       C008  Microsoft      Surface     Intel i5   8GB
7       C009    Samsung  Galaxy Book     Intel i7  16GB

In [175]:
pd.concat([df_computers1,df_computers2], axis = 1) # for this table this is not a good concatenation

,ComputerID,Brand,Model,Processor,RAM,ComputerID,Brand,Model,Processor,RAM
0,C001,Dell,Inspiron,Intel i5,8GB,C006,Asus,ZenBook,Intel i9,16GB
1,C002,HP,Pavilion,Intel i7,16GB,C007,Acer,Aspire,AMD Ryzen 7,8GB
2,C003,Apple,MacBook,M1,8GB,C008,Microsoft,Surface,Intel i5,8GB
3,C004,Lenovo,ThinkPad,AMD Ryzen 5,16GB,C009,Samsung,Galaxy Book,Intel i7,16GB

In [176]:
df_computers3 = pd.DataFrame({
    'ComputerID': ['C001', 'C002', 'C003', 'C005'],
    'Storage': ['256GB SSD', '512GB SSD', '256GB SSD', '1TB HDD'],
    'Graphics': ['Intel UHD', 'NVIDIA GTX 1650', 'Apple GPU', 'AMD Radeon'],
    'Price': [700, 1200, 1500, 800]
})
df_computers3

  ComputerID    Storage         Graphics  Price
0       C001  256GB SSD        Intel UHD    700
1       C002  512GB SSD  NVIDIA GTX 1650   1200
2       C003  256GB SSD        Apple GPU   1500
3       C005    1TB HDD       AMD Radeon    800

In [177]:
df_computers1

  ComputerID   Brand     Model    Processor   RAM
0       C001    Dell  Inspiron     Intel i5   8GB
1       C002      HP  Pavilion     Intel i7  16GB
2       C003   Apple   MacBook           M1   8GB
3       C004  Lenovo  ThinkPad  AMD Ryzen 5  16GB

In [178]:
df_computers3

  ComputerID    Storage         Graphics  Price
0       C001  256GB SSD        Intel UHD    700
1       C002  512GB SSD  NVIDIA GTX 1650   1200
2       C003  256GB SSD        Apple GPU   1500
3       C005    1TB HDD       AMD Radeon    800

In [179]:
pd.merge(df_computers1, df_computers3)

,ComputerID,Brand,Model,Processor,RAM,Storage,Graphics,Price
0,C001,Dell,Inspiron,Intel i5,8GB,256GB SSD,Intel UHD,700
1,C002,HP,Pavilion,Intel i7,16GB,512GB SSD,NVIDIA GTX 1650,1200
2,C003,Apple,MacBook,M1,8GB,256GB SSD,Apple GPU,1500

In [180]:
pd.merge(df_computers1,df_computers3, on='ComputerID',how='inner')

,ComputerID,Brand,Model,Processor,RAM,Storage,Graphics,Price
0,C001,Dell,Inspiron,Intel i5,8GB,256GB SSD,Intel UHD,700
1,C002,HP,Pavilion,Intel i7,16GB,512GB SSD,NVIDIA GTX 1650,1200
2,C003,Apple,MacBook,M1,8GB,256GB SSD,Apple GPU,1500

In [181]:
df_computers3

  ComputerID    Storage         Graphics  Price
0       C001  256GB SSD        Intel UHD    700
1       C002  512GB SSD  NVIDIA GTX 1650   1200
2       C003  256GB SSD        Apple GPU   1500
3       C005    1TB HDD       AMD Radeon    800

In [182]:
pd.merge(df_computers1,df_computers3, on='ComputerID',how='left')

,ComputerID,Brand,Model,Processor,RAM,Storage,Graphics,Price
0,C001,Dell,Inspiron,Intel i5,8GB,256GB SSD,Intel UHD,700.0
1,C002,HP,Pavilion,Intel i7,16GB,512GB SSD,NVIDIA GTX 1650,1200.0
2,C003,Apple,MacBook,M1,8GB,256GB SSD,Apple GPU,1500.0
3,C004,Lenovo,ThinkPad,AMD Ryzen 5,16GB,NaN,NaN,NaN

In [183]:
pd.merge(df_computers1,df_computers3, on='ComputerID',how='right')

,ComputerID,Brand,Model,Processor,RAM,Storage,Graphics,Price
0,C001,Dell,Inspiron,Intel i5,8GB,256GB SSD,Intel UHD,700
1,C002,HP,Pavilion,Intel i7,16GB,512GB SSD,NVIDIA GTX 1650,1200
2,C003,Apple,MacBook,M1,8GB,256GB SSD,Apple GPU,1500
3,C005,NaN,NaN,NaN,NaN,1TB HDD,AMD Radeon,800

In [184]:
pd.merge(df_computers1,df_computers3, on='ComputerID',how='outer')

,ComputerID,Brand,Model,Processor,RAM,Storage,Graphics,Price
0,C001,Dell,Inspiron,Intel i5,8GB,256GB SSD,Intel UHD,700.0
1,C002,HP,Pavilion,Intel i7,16GB,512GB SSD,NVIDIA GTX 1650,1200.0
2,C003,Apple,MacBook,M1,8GB,256GB SSD,Apple GPU,1500.0
3,C004,Lenovo,ThinkPad,AMD Ryzen 5,16GB,NaN,NaN,NaN
4,C005,NaN,NaN,NaN,NaN,1TB HDD,AMD Radeon,800.0

In [185]:
df_employees = pd.DataFrame({
    'EmployeeID': ['E001', 'E002', 'E003', 'E004'],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'Engineering', 'Marketing', 'Finance']
})
df_employees

  EmployeeID     Name   Department
0       E001    Alice           HR
1       E002      Bob  Engineering
2       E003  Charlie    Marketing
3       E004    David      Finance

In [186]:
df_salaries = pd.DataFrame({
    'EmployeeID': ['E001', 'E002', 'E005', 'E006'],
    'Salary': [50000, 60000, 70000, 80000]
})
df_salaries

  EmployeeID  Salary
0       E001   50000
1       E002   60000
2       E005   70000
3       E006   80000

In [ ]:
df_employees.join(df_salaries) # ERROR --> overlap

ValueError: columns overlap but no suffix specified: Index(['EmployeeID'], dtype='object')

In [190]:
df_employees.set_index('EmployeeID').join(df_salaries.set_index('EmployeeID'), how = 'inner')

             Name   Department  Salary
EmployeeID
E001        Alice           HR   50000
E002          Bob  Engineering   60000

In [191]:
df_employees

  EmployeeID     Name   Department
0       E001    Alice           HR
1       E002      Bob  Engineering
2       E003  Charlie    Marketing
3       E004    David      Finance

In [193]:
df_salaries.set_index('EmployeeID', inplace = True)

In [195]:
df_employees.join(df_salaries, how = 'outer')

     EmployeeID     Name   Department   Salary
0          E001    Alice           HR      NaN
1          E002      Bob  Engineering      NaN
2          E003  Charlie    Marketing      NaN
3          E004    David      Finance      NaN
E001        NaN      NaN          NaN  50000.0
E002        NaN      NaN          NaN  60000.0
E005        NaN      NaN          NaN  70000.0
E006        NaN      NaN          NaN  80000.0