# Combining DataFrames

In [130]:
import pandas as pd
import numpy as np
import seaborn as sns

In [131]:
import warnings
warnings.filterwarnings('ignore')

In [132]:
one = pd.DataFrame({
   'name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5'],
   'marks_scored':[98,90,87,69,78]},
   index=[1,2,3,4,5])

two = pd.DataFrame({
   'name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5'],
   'marks_scored':[89,80,79,97,88]},
   index=[1,2,3,4,5])

In [133]:
one

     name subject_id  marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78

In [134]:
two

    name subject_id  marks_scored
1  Billy       sub2            89
2  Brian       sub4            80
3   Bran       sub3            79
4  Bryce       sub6            97
5  Betty       sub5            88

## concat()

In [135]:
pd.concat([one, two])

     name subject_id  marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88

In [136]:
pd.concat([one, two], ignore_index = True)

     name subject_id  marks_scored
0    Alex       sub1            98
1     Amy       sub2            90
2   Allen       sub4            87
3   Alice       sub6            69
4  Ayoung       sub5            78
5   Billy       sub2            89
6   Brian       sub4            80
7    Bran       sub3            79
8   Bryce       sub6            97
9   Betty       sub5            88

In [137]:
pd.concat([one, two], axis = 1) # not a very sensible concationation method

     name subject_id  marks_scored   name subject_id  marks_scored
1    Alex       sub1            98  Billy       sub2            89
2     Amy       sub2            90  Brian       sub4            80
3   Allen       sub4            87   Bran       sub3            79
4   Alice       sub6            69  Bryce       sub6            97
5  Ayoung       sub5            78  Betty       sub5            88

In [138]:
pd.concat([one, two], ignore_index = True, axis = 1)

        0     1   2      3     4   5
1    Alex  sub1  98  Billy  sub2  89
2     Amy  sub2  90  Brian  sub4  80
3   Allen  sub4  87   Bran  sub3  79
4   Alice  sub6  69  Bryce  sub6  97
5  Ayoung  sub5  78  Betty  sub5  88

## merge()

In [139]:
x = pd.DataFrame({'product': ['pants', 'shirt', 'cap','boat'],
                     'Ankara': [3,4,6,0],
                     'Bursa': [0,5,2,8]})

y = pd.DataFrame({'product': ['pants', 'shirt', 'cap','coat'],
                          'Istanbul': [2,1,0,7],
                          'Izmir': [3,2,2,0]})

In [140]:
x

  product  Ankara  Bursa
0   pants       3      0
1   shirt       4      5
2     cap       6      2
3    boat       0      8

In [141]:
y

  product  Istanbul  Izmir
0   pants         2      3
1   shirt         1      2
2     cap         0      2
3    coat         7      0

In [142]:
pd.merge(x, y) # as default it makes inner join
# it gets the common data from both dataframes

  product  Ankara  Bursa  Istanbul  Izmir
0   pants       3      0         2      3
1   shirt       4      5         1      2
2     cap       6      2         0      2

In [143]:
pd.merge(x, y, how = 'left')

  product  Ankara  Bursa  Istanbul  Izmir
0   pants       3      0       2.0    3.0
1   shirt       4      5       1.0    2.0
2     cap       6      2       0.0    2.0
3    boat       0      8       NaN    NaN

In [144]:
pd.merge(x, y, how = 'left', on = 'product')
# when you have multiple common fileds you can use the on attribute

  product  Ankara  Bursa  Istanbul  Izmir
0   pants       3      0       2.0    3.0
1   shirt       4      5       1.0    2.0
2     cap       6      2       0.0    2.0
3    boat       0      8       NaN    NaN

In [145]:
pd.merge(x, y, how = 'right', on = 'product')

  product  Ankara  Bursa  Istanbul  Izmir
0   pants     3.0    0.0         2      3
1   shirt     4.0    5.0         1      2
2     cap     6.0    2.0         0      2
3    coat     NaN    NaN         7      0

In [146]:
pd.merge(x, y, how = 'outer', on = 'product')

  product  Ankara  Bursa  Istanbul  Izmir
0    boat     0.0    8.0       NaN    NaN
1     cap     6.0    2.0       0.0    2.0
2    coat     NaN    NaN       7.0    0.0
3   pants     3.0    0.0       2.0    3.0
4   shirt     4.0    5.0       1.0    2.0

In [147]:
 df1 = pd.DataFrame({'lkey': ['x', 'y', 'z', 'x'],
                    'lvalue': [2, 3, 5, 7]})

df2 = pd.DataFrame({'rkey': ['a', 'x', 'z', 'b'],
                    'rvalue': [7, 8, 9, 10]})

In [148]:
df1

  lkey  lvalue
0    x       2
1    y       3
2    z       5
3    x       7

In [149]:
df2

  rkey  rvalue
0    a       7
1    x       8
2    z       9
3    b      10

In [ ]:
pd.merge(df1, df2, how = 'inner') # ERROR -->  No common columns to perform merge on.

In [151]:
pd.merge(df1, df2, how = 'inner', left_on = 'lkey', right_on = 'rkey')

  lkey  lvalue rkey  rvalue
0    x       2    x       8
1    z       5    z       9
2    x       7    x       8

In [152]:
pd.merge(df1, df2, how = 'left', left_on = 'lkey', right_on = 'rkey')

  lkey  lvalue rkey  rvalue
0    x       2    x     8.0
1    y       3  NaN     NaN
2    z       5    z     9.0
3    x       7    x     8.0

## join()

In [153]:
df3 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index = ['K0', 'K1', 'K2']) 

df4 = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index = ['K0', 'K2', 'K3'])

In [154]:
df3

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [155]:
df4

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [156]:
df3.join(df4)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [157]:
df4.join(df3)

     C   D    A    B
K0  C0  D0   A0   B0
K2  C2  D2   A2   B2
K3  C3  D3  NaN  NaN

In [158]:
df3.join(df4, how = 'outer') # fully joined, no data loss

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [159]:
df5 = pd.DataFrame({'key': ['K0', 'K2', 'K3', 'K4', 'K5', 'K6'],
                   'X': ['X0', 'X2', 'X3', 'X4', 'X5', 'X6']})

df6 = pd.DataFrame({'key': ['K0', 'K2', 'K3'],
                      'Y': ['Y0', 'Y2', 'Y3']})

In [160]:
df5

  key   X
0  K0  X0
1  K2  X2
2  K3  X3
3  K4  X4
4  K5  X5
5  K6  X6

In [161]:
df6

  key   Y
0  K0  Y0
1  K2  Y2
2  K3  Y3

In [ ]:
df5.join(df6) # ERROR --> columns overlap

In [163]:
df5.join(df6, lsuffix = 'left')

  keyleft   X  key    Y
0      K0  X0   K0   Y0
1      K2  X2   K2   Y2
2      K3  X3   K3   Y3
3      K4  X4  NaN  NaN
4      K5  X5  NaN  NaN
5      K6  X6  NaN  NaN

In [164]:
df5.join(df6, lsuffix = 'left', rsuffix = 'right')

  keyleft   X keyright    Y
0      K0  X0       K0   Y0
1      K2  X2       K2   Y2
2      K3  X3       K3   Y3
3      K4  X4      NaN  NaN
4      K5  X5      NaN  NaN
5      K6  X6      NaN  NaN

# Text Data - String Methods

**str.lower():** Converts a string to lowercase

**str.upper():** Converts a string to uppercase

**str.capitalize():** Converts the first character to uppercase

**str.title():** Converts the first character of each word to uppercase

**str.swapcase():** Converts uppercase letters to lowercase and lowercase letters to uppercase

**str.isalpha():** Returns True or False by checking whether all characters are in the alphabet.

**str.isnumeric():** Checks whether all characters contain numeric values and returns True or False

**str.isalnum():** Returns True or False by checking whether all characters contain letters or numeric values

**str.endswith():** Returns True or False by checking that a string ends with the specified value

**str.startswith():** Returns True or False by checking that a string starts with the specified value

**str.contains():** Checks whether a substring is contained in a string, returning True or False for each element

**str.strip():** Removes leading and trailing spaces from a string and returns a trimmed version

**str.replace():** Returns a string with a specified value replaced by another value.

**str.split():** Splits a string at the specified delimiter and returns a list

**str.find():** Searches for a specified value in a string and returns the index of its location

**str.findall():** Returns a list of all instances in a pattern

**str.join():** Converts the elements of an iterable to a string

In [165]:
df = pd.DataFrame(data=[['Tyler DURDEN', 'HR', "manager", "$180,000", 55],
                        ['MARIA puder', "IT", "data analyst", "150000dolar", 28],
                        ['dorothy gale', "HR", "recruiter", "$120,000", 30],
                        ['Edmond Dantes', "IT", "data scientist", "$170,000","-"], 
                        ['Gregor SAMSA',"IT", "frontend developer", "120000dolar",32]],
                  columns=["name","dept", "job", "salary", "age"])
df

            name dept                 job       salary age
0   Tyler DURDEN   HR             manager     $180,000  55
1    MARIA puder   IT        data analyst  150000dolar  28
2   dorothy gale   HR           recruiter     $120,000  30
3  Edmond Dantes   IT      data scientist     $170,000   -
4   Gregor SAMSA   IT  frontend developer  120000dolar  32

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   job     5 non-null      object
 3   salary  5 non-null      object
 4   age     5 non-null      object
dtypes: object(5)
memory usage: 332.0+ bytes

In [167]:
df.name.str.title()

0     Tyler Durden
1      Maria Puder
2     Dorothy Gale
3    Edmond Dantes
4     Gregor Samsa
Name: name, dtype: object

In [168]:
'welcome melisa'.title()

'Welcome Melisa'

In [169]:
df.name

0     Tyler DURDEN
1      MARIA puder
2     dorothy gale
3    Edmond Dantes
4     Gregor SAMSA
Name: name, dtype: object

In [170]:
df.name =df.name.str.title() # because inplace = True doesnt work, 
# we make an assignment to make the change permanent

In [171]:
df.name

0     Tyler Durden
1      Maria Puder
2     Dorothy Gale
3    Edmond Dantes
4     Gregor Samsa
Name: name, dtype: object

In [172]:
df.age.str.isnumeric()

0      NaN
1      NaN
2      NaN
3    False
4      NaN
Name: age, dtype: object

In [173]:
df.age.astype('str').str.isnumeric()

0     True
1     True
2     True
3    False
4     True
Name: age, dtype: bool

In [174]:
df.age.astype('str').str.isnumeric().sum()

np.int64(4)

In [175]:
df['age'].replace('-', np.nan, inplace = True)

In [176]:
df

            name dept                 job       salary   age
0   Tyler Durden   HR             manager     $180,000  55.0
1    Maria Puder   IT        data analyst  150000dolar  28.0
2   Dorothy Gale   HR           recruiter     $120,000  30.0
3  Edmond Dantes   IT      data scientist     $170,000   NaN
4   Gregor Samsa   IT  frontend developer  120000dolar  32.0

In [177]:
df.salary.str.startswith('$').sum()

np.int64(3)

In [178]:
# contains
df.job == 'data analyst'

0    False
1     True
2    False
3    False
4    False
Name: job, dtype: bool

In [179]:
df[df.job == 'data analyst']

          name dept           job       salary   age
1  Maria Puder   IT  data analyst  150000dolar  28.0

In [180]:
df[df.job.str.contains('data')]

            name dept             job       salary   age
1    Maria Puder   IT    data analyst  150000dolar  28.0
3  Edmond Dantes   IT  data scientist     $170,000   NaN

In [181]:
df

            name dept                 job       salary   age
0   Tyler Durden   HR             manager     $180,000  55.0
1    Maria Puder   IT        data analyst  150000dolar  28.0
2   Dorothy Gale   HR           recruiter     $120,000  30.0
3  Edmond Dantes   IT      data scientist     $170,000   NaN
4   Gregor Samsa   IT  frontend developer  120000dolar  32.0

In [182]:
df.salary.str.strip('$dolar')

0    180,000
1     150000
2    120,000
3    170,000
4     120000
Name: salary, dtype: object

In [183]:
df.salary.str.strip('dolar')
# strip function only looks at the beginning and the end

0    $180,000
1      150000
2    $120,000
3    $170,000
4      120000
Name: salary, dtype: object

In [184]:
df.salary.str.strip('$dolar').str.replace(',', '')

0    180000
1    150000
2    120000
3    170000
4    120000
Name: salary, dtype: object

In [185]:
df.salary.str.strip('$dolar').str.replace(',', '').astype(int)

0    180000
1    150000
2    120000
3    170000
4    120000
Name: salary, dtype: int64

In [186]:
df.salary = df.salary.str.strip('$dolar').str.replace(',', '').astype(int)
df.salary
# by assigning we made the change permanent

0    180000
1    150000
2    120000
3    170000
4    120000
Name: salary, dtype: int64

In [187]:
df

            name dept                 job  salary   age
0   Tyler Durden   HR             manager  180000  55.0
1    Maria Puder   IT        data analyst  150000  28.0
2   Dorothy Gale   HR           recruiter  120000  30.0
3  Edmond Dantes   IT      data scientist  170000   NaN
4   Gregor Samsa   IT  frontend developer  120000  32.0

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   job     5 non-null      object
 3   salary  5 non-null      int64
 4   age     4 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

# Dummy Operations

**get_dummies()** is a function commonly used in machine learning and data analysis.

In [189]:
df

            name dept                 job  salary   age
0   Tyler Durden   HR             manager  180000  55.0
1    Maria Puder   IT        data analyst  150000  28.0
2   Dorothy Gale   HR           recruiter  120000  30.0
3  Edmond Dantes   IT      data scientist  170000   NaN
4   Gregor Samsa   IT  frontend developer  120000  32.0

In [191]:
pd.get_dummies(df.dept)

      HR     IT
0   True  False
1  False   True
2   True  False
3  False   True
4  False   True

In [192]:
pd.get_dummies(df.dept, drop_first = True)

      IT
0  False
1   True
2  False
3   True
4   True

In [193]:
pd.get_dummies(df.job)

   data analyst  data scientist  frontend developer  manager  recruiter
0         False           False               False     True      False
1          True           False               False    False      False
2         False           False               False    False       True
3         False            True               False    False      False
4         False           False                True    False      False

In [194]:
pd.get_dummies(df.job, drop_first = True)

   data scientist  frontend developer  manager  recruiter
0           False               False     True      False
1           False               False    False      False
2           False               False    False       True
3            True               False    False      False
4           False                True    False      False

In [ ]:
pd.get_dummies(df) # this is not sensible

,salary,age,name_Dorothy Gale,name_Edmond Dantes,name_Gregor Samsa,name_Maria Puder,name_Tyler Durden,dept_HR,dept_IT,job_data analyst,job_data scientist,job_frontend developer,job_manager,job_recruiter
0,180000,55.0,False,False,False,False,True,True,False,False,False,False,True,False
1,150000,28.0,False,False,False,True,False,False,True,True,False,False,False,False
2,120000,30.0,True,False,False,False,False,True,False,False,False,False,False,True
3,170000,NaN,False,True,False,False,False,False,True,False,True,False,False,False
4,120000,32.0,False,False,True,False,False,False,True,False,False,True,False,False

In [197]:
pd.get_dummies(df, columns = ['dept', 'job']) # specified two columns

,name,salary,age,dept_HR,dept_IT,job_data analyst,job_data scientist,job_frontend developer,job_manager,job_recruiter
0,Tyler Durden,180000,55.0,True,False,False,False,False,True,False
1,Maria Puder,150000,28.0,False,True,True,False,False,False,False
2,Dorothy Gale,120000,30.0,True,False,False,False,False,False,True
3,Edmond Dantes,170000,NaN,False,True,False,True,False,False,False
4,Gregor Samsa,120000,32.0,False,True,False,False,True,False,False

In [198]:
df_result = pd.get_dummies(df, columns = ['dept', 'job']) 
df_result

,name,salary,age,dept_HR,dept_IT,job_data analyst,job_data scientist,job_frontend developer,job_manager,job_recruiter
0,Tyler Durden,180000,55.0,True,False,False,False,False,True,False
1,Maria Puder,150000,28.0,False,True,True,False,False,False,False
2,Dorothy Gale,120000,30.0,True,False,False,False,False,False,True
3,Edmond Dantes,170000,NaN,False,True,False,True,False,False,False
4,Gregor Samsa,120000,32.0,False,True,False,False,True,False,False

In [202]:
df_result.to_csv('df_result.csv')

In [204]:
pd.read_csv('df_result.csv')

,Unnamed: 0,name,salary,age,dept_HR,dept_IT,job_data analyst,job_data scientist,job_frontend developer,job_manager,job_recruiter
0,0,Tyler Durden,180000,55.0,True,False,False,False,False,True,False
1,1,Maria Puder,150000,28.0,False,True,True,False,False,False,False
2,2,Dorothy Gale,120000,30.0,True,False,False,False,False,False,True
3,3,Edmond Dantes,170000,NaN,False,True,False,True,False,False,False
4,4,Gregor Samsa,120000,32.0,False,True,False,False,True,False,False

In [212]:
pd.read_csv('df_result.csv', index_col = 0)

,name,salary,age,dept_HR,dept_IT,job_data analyst,job_data scientist,job_frontend developer,job_manager,job_recruiter
0,Tyler Durden,180000,55.0,True,False,False,False,False,True,False
1,Maria Puder,150000,28.0,False,True,True,False,False,False,False
2,Dorothy Gale,120000,30.0,True,False,False,False,False,False,True
3,Edmond Dantes,170000,NaN,False,True,False,True,False,False,False
4,Gregor Samsa,120000,32.0,False,True,False,False,True,False,False

In [208]:
df_result.to_csv('df_result1.csv', index = False)
# if you dont change the name you made before it overwrites it.
# by using index = False we didnt get the previous indexes

In [210]:
pd.read_csv('df_result1.csv')

,name,salary,age,dept_HR,dept_IT,job_data analyst,job_data scientist,job_frontend developer,job_manager,job_recruiter
0,Tyler Durden,180000,55.0,True,False,False,False,False,True,False
1,Maria Puder,150000,28.0,False,True,True,False,False,False,False
2,Dorothy Gale,120000,30.0,True,False,False,False,False,False,True
3,Edmond Dantes,170000,NaN,False,True,False,True,False,False,False
4,Gregor Samsa,120000,32.0,False,True,False,False,True,False,False

In [211]:
df_result.to_excel('df_result.xlsx', index = False)

In [214]:
pd.read_excel('df_result.xlsx')

,name,salary,age,dept_HR,dept_IT,job_data analyst,job_data scientist,job_frontend developer,job_manager,job_recruiter
0,Tyler Durden,180000,55.0,True,False,False,False,False,True,False
1,Maria Puder,150000,28.0,False,True,True,False,False,False,False
2,Dorothy Gale,120000,30.0,True,False,False,False,False,False,True
3,Edmond Dantes,170000,NaN,False,True,False,True,False,False,False
4,Gregor Samsa,120000,32.0,False,True,False,False,True,False,False

In [216]:
df_html = pd.read_html('https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population')

HTTPError: HTTP Error 403: Forbidden

In [215]:
df_html

NameError: name 'df_html' is not defined